name = "Syntax"
version = "0.0.2"
authors = ["Scott Tolinski"]
description = "A new take on a Syntax.fm theme. Yellows/Teals/Reds"
repository = "https://github.com/syntaxfm/syntax-zed-theme"
id = "syntax"
schema_version = 1
